name: CI/CD Docker Deployment to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Deploy on EC2 via SSH
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e
            cd /home/ec2-user/cicd-docker-app

            # Stop & remove old container if exists
            sudo docker stop cicd-app || true
            sudo docker rm cicd-app || true

            # Build new Docker image
            sudo docker build -t cicd-app .

            # Run the container in detached mode, map port 80
            sudo docker run -d -p 80:80 --name cicd-app cicd-app

            # Verify container is running
            sudo docker ps


