name: SSH Test

on:
  push:
    branches:
      - main

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            whoami
            hostname
            pwd
            echo "SSH CONNECTION SUCCESSFUL"
